id: D42911604
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:42:15+00:00'
last_modified: '2022-05-26T11:19:02.765270+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    54c5:
      image_group_id: I1PD95871
      title: གསང་བ་ཐུགས་ཀྱི་སྒྲོན་མ།
      total_pages: 1902
      order: 26
      base_file: 54c5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
