id: a346cad8a44d4d5fa64dc7f0430fe104
initial_creation_type: ocr
source_metadata:
  volumes:
    4e71bd01ac35453a9f9122b39cac1832:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
